import type { Metadata } from "next";
import { Sarabun } from "next/font/google";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import { Theme, ThemePanel } from "@radix-ui/themes";

const sarabun = Sarabun({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin", "thai"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sarabun.className} suppressHydrationWarning>
        {/* set dark mode */}
        <Theme appearance="dark">
          <ThemePanel />
          {children}
        </Theme>
      </body>
    </html>
  );
}
